name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * 3"  # Quarta-feira à meia-noite
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Pacman Graph
        uses: tody-lo/pacman-contribution-graph@v1
        with:
          username: lorocks51987
          theme: dark
          output_path: ./output/pacman

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: output/pacman
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
