name: Generate pacman animation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # roda todo dia à meia-noite

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gera o SVG do Pacman
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Verifica arquivos gerados
        run: ls -la

      - name: Move o arquivo gerado para a pasta output
        run: |
          mkdir -p output
          mv pacman-contribution-graph.svg output/

      - name: Publica na branch 'output'
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
