name: Generate pacman animation

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checa o repositório
        uses: actions/checkout@v3

      - name: Instala dependências
        run: sudo apt-get install -y python3 python3-pip git

      - name: Baixa o script do Pacman
        run: curl -sSL https://raw.githubusercontent.com/abozanona/pacman-contribution-graph/main/pacman-contribution-graph.py -o pacman.py

      - name: Roda o script com seu usuário
        run: python3 pacman.py lorocks51987

      - name: Mostra os arquivos gerados
        run: find . -type f

      - name: Cria pasta output e move o SVG
        run: |
          mkdir -p output
          mv pacman-contribution-graph.svg output/

      - name: Publica na branch `output`
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
