name: Generate Pacman Animation

on:
  schedule:
    - cron: "0 0 * * *" # roda todo dia às 00:00
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Pacman Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            ./output/pacman-contribution-graph.svg
            ./output/pacman-contribution-graph-dark.svg
        env:
          TYPE: pacman

      - name: Commit and Push
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: 🟢 Gerando gráfico Pacman
          add: './output'
