name: Generate pacman contribution graph

on:
  schedule:
    - cron: "0 0 * * *"  # roda todos os dias à meia-noite
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install -g @jakejarvis/pacman-canvas

      - name: Generate Pac-Man SVG
        run: |
          mkdir -p output
          pacman-canvas --username lorocks51987 --output ./output/pacman.svg

      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          message: "Atualiza gráfico Pac-Man 🟢"
          add: 'output/pacman.svg'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
