name: generate-and-upload-card

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v4
        
      - name: Gerar Card Pixel Art
        uses: LuciNyan/pixel-profile/action@main
        with:
          crt_outputs: |
            dist/pixel-profile-crt.svg?username=lorocks51987
            
      - name: Commit e Push automatico
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Atualizando estatisticas Pixel Art (CRT)"
